// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbmlsdftletwtmnxhswk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZibWxzZGZ0bGV0d3Rtbnhoc3drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NDg3MDEsImV4cCI6MjA3MzIyNDcwMX0.9TRO_nnxBxDI_oLMnYoELUogdwxsSJwELzNRxka_EUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});